# Generated by Django 2.2.7 on 2019-11-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('id_cliente', models.CharField(max_length=35)),
                ('id_mesero', models.CharField(max_length=35)),
                ('tiempo_llegada_cliente', models.TimeField(auto_now_add=True)),
                ('tiempo_total_cliente', models.CharField(max_length=35)),
                ('tiempo_inicio_limpieza', models.TimeField(auto_now_add=True)),
                ('tiempo_total_limpieza', models.IntegerField()),
                ('tiempo_total_servicio', models.IntegerField()),
            ],
        ),
    ]
