# Generated by Django 2.2.7 on 2019-11-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_mesa_comodidad'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='codigo',
        ),
        migrations.AddField(
            model_name='servicio',
            name='mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mesas.Mesa'),
            preserve_default=False,
        ),
    ]
