# Generated by Django 2.2.7 on 2019-11-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=35, unique=True)),
                ('disponible', models.BooleanField(default=True)),
                ('ocupado_limpieza', models.BooleanField(default=True)),
                ('ocupado_cliente', models.BooleanField(default=True)),
                ('capacidad_sillas', models.IntegerField()),
                ('calidad', models.IntegerField()),
            ],
        ),
    ]
