# Generated by Django 2.2.7 on 2019-11-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_mesa_comodidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='ocupado_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='ocupado_limpieza',
            field=models.BooleanField(default=False),
        ),
    ]
